// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqwrljuzahidiohpmkml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxd3JsanV6YWhpZGlvaHBta21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTg4MDAsImV4cCI6MjA3MTgzNDgwMH0.WDrVfozXYkWCLYr4zOzdlNjXbAb_-13KCsWlUEgUYiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});